-- ==========================================================
-- PROYECTO: BYCAR
-- FASE: Esquema normalizado (3FN) para PostgreSQL (Supabase)
-- ORIGEN: scripts/tablas_DDL.txt (Oracle). Mismas tablas, columnas,
--         restricciones y nombres de constraints.
--
-- Equivalencias de tipos:
--   NUMBER (ids y claves)          → BIGINT   (los ids se generan con Date.now())
--   NUMBER (sin uso de id)         → NUMERIC
--   NUMBER(10,2)                   → NUMERIC(10,2)
--   VARCHAR2(n BYTE)               → VARCHAR(n)
--   CLOB                           → TEXT
--   DATE (fecha y hora, sin zona)  → TIMESTAMP(0)
--   TIMESTAMP WITH LOCAL TIME ZONE → TIMESTAMPTZ
--   SYSDATE                        → LOCALTIMESTAMP(0)
--
-- Los NOT NULL que en Oracle eran CHECK (... IS NOT NULL) siguen siendo CHECK:
-- así /api/admin/tablas informa NULLABLE igual que antes.
--
-- ⚠️ Empieza borrando las tablas: correrlo sobre una base con datos los elimina.
-- ==========================================================

BEGIN;

-- ==========================================================
-- BORRADO PREVIO (orden inverso a jerarquía de dependencias)
-- ==========================================================

DROP TABLE IF EXISTS GUARDIANES CASCADE;
DROP TABLE IF EXISTS SOLICITUDES CASCADE;
DROP TABLE IF EXISTS MENSAJES CASCADE;
DROP TABLE IF EXISTS VIAJES CASCADE;
DROP TABLE IF EXISTS VEHICULOS CASCADE;
DROP TABLE IF EXISTS PERMISOS CASCADE;
DROP TABLE IF EXISTS USUARIOS CASCADE;
DROP TABLE IF EXISTS PERFILES CASCADE;
DROP TABLE IF EXISTS MENUS CASCADE;
DROP TABLE IF EXISTS MARCAS CASCADE;
DROP TABLE IF EXISTS MUNICIPIOS CASCADE;
DROP TABLE IF EXISTS DEPARTAMENTOS CASCADE;
DROP TABLE IF EXISTS ESTADOS_SOL CASCADE;
DROP TABLE IF EXISTS ESTADOS_VIA CASCADE;
DROP TABLE IF EXISTS ESTADOS_GUA CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;

-- ==========================================================
-- TABLA: ROLES
-- ==========================================================

CREATE TABLE ROLES (
    ID_ROL BIGINT,
    NOMBRE_ROL VARCHAR(20),
    CREDENCIAL_ROL VARCHAR(15),
    CONSTRAINT PK_ROLES PRIMARY KEY(ID_ROL),
    CONSTRAINT NN_NOMBRE_ROL
        CHECK(NOMBRE_ROL IS NOT NULL),
    CONSTRAINT NN_CREDENCIAL_ROL
        CHECK(CREDENCIAL_ROL IS NOT NULL)
);

-- ==========================================================
-- TABLA: MENUS
-- ==========================================================

CREATE TABLE MENUS (
    ID_ENU BIGINT,
    CAMPO_ENU VARCHAR(20),
    URL_ENU VARCHAR(100),
    MENU_ID_ENU BIGINT,
    CONSTRAINT PK_MENU PRIMARY KEY(ID_ENU),
    CONSTRAINT NN_CAMPO_ENU
        CHECK(CAMPO_ENU IS NOT NULL),
    CONSTRAINT NN_URL_ENU
        CHECK(URL_ENU IS NOT NULL),
    CONSTRAINT FK_MENU_MENU
        FOREIGN KEY(MENU_ID_ENU)
        REFERENCES MENUS (ID_ENU)
        ON DELETE CASCADE
);

-- ==========================================================
-- TABLA: PERFILES
-- ==========================================================

CREATE TABLE PERFILES (
    ID_PER BIGINT,
    NOMBRE_PER VARCHAR(15),
    ROLES_ID_ROL BIGINT,
    CONSTRAINT PK_PERFIL PRIMARY KEY(ID_PER),
    CONSTRAINT NN_NOMBRE_PER
        CHECK(NOMBRE_PER IS NOT NULL),
    CONSTRAINT FK_PERFIL_ROLES
        FOREIGN KEY(ROLES_ID_ROL)
        REFERENCES ROLES (ID_ROL)
        ON DELETE CASCADE
);

-- ==========================================================
-- TABLA: USUARIOS
-- ==========================================================

CREATE TABLE USUARIOS (
    ID_USU BIGINT,
    NOMBRE_USU VARCHAR(100) NOT NULL,
    APELLIDO_USU VARCHAR(100) NOT NULL,
    CORREO_USU VARCHAR(150) NOT NULL UNIQUE,
    CONTRASENA_USU VARCHAR(255) NOT NULL,
    PERFIL_ID_PER BIGINT NOT NULL,
    FECHA_CREACION TIMESTAMP(0) DEFAULT LOCALTIMESTAMP(0),
    CONSTRAINT PK_USUARIOS
        PRIMARY KEY(ID_USU),
    CONSTRAINT FK_USUARIOS_PERFIL
        FOREIGN KEY(PERFIL_ID_PER)
        REFERENCES PERFILES (ID_PER)
        ON DELETE CASCADE
);

-- ==========================================================
-- TABLA: PERMISOS
-- ==========================================================

CREATE TABLE PERMISOS (
    USUARIO_ID_USU BIGINT,
    MENU_ID_ENU BIGINT,
    CONSTRAINT PK_PERMISOS
        PRIMARY KEY(USUARIO_ID_USU, MENU_ID_ENU),
    CONSTRAINT FK_PERMISOS_USUARIO
        FOREIGN KEY(USUARIO_ID_USU)
        REFERENCES USUARIOS (ID_USU)
        ON DELETE CASCADE,
    CONSTRAINT FK_PERMISOS_MENU
        FOREIGN KEY(MENU_ID_ENU)
        REFERENCES MENUS (ID_ENU)
        ON DELETE CASCADE
);

-- ==========================================================
-- TABLA: MARCAS
-- ==========================================================

CREATE TABLE MARCAS (
    ID_MAR BIGINT,
    NOMBRE_MAR VARCHAR(20),
    CONSTRAINT PK_MARCA PRIMARY KEY(ID_MAR),
    CONSTRAINT NN_NOMBRE_MAR
        CHECK(NOMBRE_MAR IS NOT NULL)
);

-- ==========================================================
-- TABLA: DEPARTAMENTOS
-- ==========================================================

CREATE TABLE DEPARTAMENTOS (
    ID_DEP BIGINT,
    NOMBRE_DEP VARCHAR(50),
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(ID_DEP),
    CONSTRAINT NN_NOMBRE_DEP
        CHECK(NOMBRE_DEP IS NOT NULL)
);

-- ==========================================================
-- TABLA: MUNICIPIOS
-- ==========================================================

CREATE TABLE MUNICIPIOS (
    ID_MUN BIGINT,
    NOMBRE_MUN VARCHAR(100),
    DEPARTAMENTO_ID_DEP BIGINT,
    CONSTRAINT PK_MUNICIPIOS PRIMARY KEY(ID_MUN),
    CONSTRAINT NN_NOMBRE_MUN
        CHECK(NOMBRE_MUN IS NOT NULL),
    CONSTRAINT NN_DEPARTAMENTO_ID_DEP
        CHECK(DEPARTAMENTO_ID_DEP IS NOT NULL),
    CONSTRAINT FK_MUNICIPIOS_DEPARTAMENTO
        FOREIGN KEY(DEPARTAMENTO_ID_DEP)
        REFERENCES DEPARTAMENTOS (ID_DEP)
        ON DELETE CASCADE
);

-- ==========================================================
-- TABLA: ESTADOS_SOL
-- ==========================================================

CREATE TABLE ESTADOS_SOL (
    ID_EST_SOL BIGINT,
    ESTADO_EST_SOL VARCHAR(15),
    CONSTRAINT PK_ESTADO_SOL PRIMARY KEY(ID_EST_SOL),
    CONSTRAINT NN_ESTADO_EST_SOL
        CHECK(ESTADO_EST_SOL IS NOT NULL)
);

-- ==========================================================
-- TABLA: ESTADOS_VIA
-- ==========================================================

CREATE TABLE ESTADOS_VIA (
    ID_EST_VIA BIGINT,
    ESTADO_EST_VIA VARCHAR(15),
    CONSTRAINT PK_ESTADO_VIA PRIMARY KEY(ID_EST_VIA),
    CONSTRAINT NN_ESTADO_EST_VIA
        CHECK(ESTADO_EST_VIA IS NOT NULL)
);

-- ==========================================================
-- TABLA: ESTADOS_GUA
-- ==========================================================

CREATE TABLE ESTADOS_GUA (
    ID_EST_GUA BIGINT,
    ESTADO_EST_GUA VARCHAR(15),
    CONSTRAINT PK_ESTADO_GUA PRIMARY KEY(ID_EST_GUA),
    CONSTRAINT NN_ESTADO_EST_GUA
        CHECK(ESTADO_EST_GUA IS NOT NULL)
);

-- ==========================================================
-- TABLA: VEHICULOS
-- ==========================================================

CREATE TABLE VEHICULOS (
    PLACA_VEH VARCHAR(6),
    CAPACIDAD_VEH INTEGER,
    CONDUCTOR_ID_USU BIGINT,
    MARCA_ID_MAR BIGINT,
    CONSTRAINT PK_VEHICULOS PRIMARY KEY(PLACA_VEH),
    CONSTRAINT NN_CAPACIDAD_VEH
        CHECK(CAPACIDAD_VEH IS NOT NULL),
    CONSTRAINT NN_CONDUCTOR_ID_USU
        CHECK(CONDUCTOR_ID_USU IS NOT NULL),
    CONSTRAINT NN_MARCA_ID_MAR
        CHECK(MARCA_ID_MAR IS NOT NULL),
    CONSTRAINT FK_VEHICULO_USUARIOS
        FOREIGN KEY(CONDUCTOR_ID_USU)
        REFERENCES USUARIOS (ID_USU)
        ON DELETE CASCADE,
    CONSTRAINT FK_VEHICULO_MARCA
        FOREIGN KEY(MARCA_ID_MAR)
        REFERENCES MARCAS (ID_MAR)
        ON DELETE CASCADE
);

-- ==========================================================
-- TABLA: VIAJES
-- ==========================================================

CREATE TABLE VIAJES (
    ID_VIA BIGINT,
    TIEMPO_SALIDA_VIA TIMESTAMP(0),
    CUPOS_DISPONIBLES_VIA INTEGER,
    COSTO_PERSONA_VIA NUMERIC(10,2),
    COMENTARIOS_VIA VARCHAR(500),
    USUARIOS_ID_USU BIGINT,
    MUNICIPIO_ORIGEN_ID BIGINT,
    MUNICIPIOS_DESTINO_ID BIGINT,
    VEHICULO_PLACA_VEH VARCHAR(6),
    ESTADO_VIA_ID_EST_VIA BIGINT,
    CONSTRAINT PK_VIAJES PRIMARY KEY(ID_VIA),
    CONSTRAINT NN_TIEMPO_SALIDA_VIA
        CHECK(TIEMPO_SALIDA_VIA IS NOT NULL),
    CONSTRAINT NN_CUPOS_DISPONIBLES_VIA
        CHECK(CUPOS_DISPONIBLES_VIA IS NOT NULL),
    CONSTRAINT NN_COSTO_PERSONA_VIA
        CHECK(COSTO_PERSONA_VIA IS NOT NULL),
    CONSTRAINT NN_USUARIOS_ID_USU
        CHECK(USUARIOS_ID_USU IS NOT NULL),
    CONSTRAINT NN_MUNICIPIO_ORIGEN_ID
        CHECK(MUNICIPIO_ORIGEN_ID IS NOT NULL),
    CONSTRAINT NN_VEHICULO_PLACA_VEH
        CHECK(VEHICULO_PLACA_VEH IS NOT NULL),
    CONSTRAINT NN_ESTADO_VIA_ID_EST_VIA
        CHECK(ESTADO_VIA_ID_EST_VIA IS NOT NULL),
    CONSTRAINT FK_VIAJES_USUARIOS
        FOREIGN KEY(USUARIOS_ID_USU)
        REFERENCES USUARIOS (ID_USU)
        ON DELETE CASCADE,
    CONSTRAINT FK_VIAJES_MUNICIPIOS_ORIGEN
        FOREIGN KEY(MUNICIPIO_ORIGEN_ID)
        REFERENCES MUNICIPIOS (ID_MUN)
        ON DELETE CASCADE,
    CONSTRAINT FK2_VIAJES_MUNICIPIOS_DESTINO
        FOREIGN KEY(MUNICIPIOS_DESTINO_ID)
        REFERENCES MUNICIPIOS (ID_MUN)
        ON DELETE CASCADE,
    CONSTRAINT FK_VIAJES_VEHICULO
        FOREIGN KEY(VEHICULO_PLACA_VEH)
        REFERENCES VEHICULOS (PLACA_VEH)
        ON DELETE CASCADE,
    CONSTRAINT FK_VIAJES_ESTADO_VIA
        FOREIGN KEY(ESTADO_VIA_ID_EST_VIA)
        REFERENCES ESTADOS_VIA (ID_EST_VIA)
        ON DELETE CASCADE
);

-- ==========================================================
-- TABLA: MENSAJES
-- ==========================================================

CREATE TABLE MENSAJES (
    ID_MEN BIGINT,
    CONTENIDO_MEN TEXT,
    FECHA_ENVIO_MEN TIMESTAMPTZ,
    USUARIO_RECEPTOR_ID BIGINT,
    USUARIOS_EMISOR_ID BIGINT,
    -- Chat al que pertenece (05_guardian_y_chats.sql). Las FK van después de crear GUARDIANES
    SOLICITUD_ID_SOL BIGINT,
    GUARDIAN_ID_GUA BIGINT,
    CONSTRAINT PK_MENSAJES PRIMARY KEY(ID_MEN),
    CONSTRAINT CK_MENSAJES_UN_CHAT
        CHECK(SOLICITUD_ID_SOL IS NULL OR GUARDIAN_ID_GUA IS NULL),
    CONSTRAINT FK_MENSAJES_USUARIOS_RECEPTOR
        FOREIGN KEY(USUARIO_RECEPTOR_ID)
        REFERENCES USUARIOS (ID_USU)
        ON DELETE CASCADE,
    CONSTRAINT FK_MENSAJES_USUARIOS_EMISOR
        FOREIGN KEY(USUARIOS_EMISOR_ID)
        REFERENCES USUARIOS (ID_USU)
        ON DELETE CASCADE
);

-- ==========================================================
-- TABLA: SOLICITUDES
-- ==========================================================

CREATE TABLE SOLICITUDES (
    ID_SOL BIGINT,
    FECHA_SOL TIMESTAMP(0),
    VIAJES_ID_VIA BIGINT,
    USUARIOS_ID_USU BIGINT,
    ESTADO_ID_EST BIGINT,
    CONSTRAINT PK_SOLICITUDES PRIMARY KEY(ID_SOL),
    CONSTRAINT FK_SOLICITUDES_USUARIOS
        FOREIGN KEY(USUARIOS_ID_USU)
        REFERENCES USUARIOS (ID_USU)
        ON DELETE CASCADE,
    CONSTRAINT FK_SOLICITUDES_VIAJES
        FOREIGN KEY(VIAJES_ID_VIA)
        REFERENCES VIAJES (ID_VIA)
        ON DELETE CASCADE,
    CONSTRAINT FK_SOLICITUDES_ESTADO
        FOREIGN KEY(ESTADO_ID_EST)
        REFERENCES ESTADOS_SOL (ID_EST_SOL)
        ON DELETE CASCADE
);

-- ==========================================================
-- TABLA: GUARDIANES
-- ==========================================================

CREATE TABLE GUARDIANES (
    ID_GUA BIGINT,
    EMAIL_CONFIANZA_GUA VARCHAR(150),
    FECHA_INICIO_GUA TIMESTAMPTZ,
    VIAJES_ID_VIA BIGINT,
    ESTADO_ID_EST BIGINT,
    TIEMPO_ESTIMADO_GUA NUMERIC,
    -- Quién activó el guardián y el usuario contacto (05_guardian_y_chats.sql)
    USUARIO_ID_USU BIGINT,
    CONTACTO_ID_USU BIGINT,
    CONSTRAINT PK_GUARDIAN PRIMARY KEY(ID_GUA),
    CONSTRAINT NN_EMAIL_CONFIANZA_GUA
         CHECK(EMAIL_CONFIANZA_GUA IS NOT NULL),
    CONSTRAINT FK_GUARDIAN_VIAJES
         FOREIGN KEY(VIAJES_ID_VIA)
         REFERENCES VIAJES (ID_VIA)
         ON DELETE CASCADE,
    CONSTRAINT FK_GUARDIAN_ESTADO
         FOREIGN KEY(ESTADO_ID_EST)
         REFERENCES ESTADOS_GUA (ID_EST_GUA)
         ON DELETE CASCADE,
    CONSTRAINT FK_GUARDIAN_USUARIO
         FOREIGN KEY(USUARIO_ID_USU)
         REFERENCES USUARIOS (ID_USU)
         ON DELETE CASCADE,
    CONSTRAINT FK_GUARDIAN_CONTACTO
         FOREIGN KEY(CONTACTO_ID_USU)
         REFERENCES USUARIOS (ID_USU)
         ON DELETE CASCADE
);

-- Mensajes: cada uno pertenece a una solicitud (pasajero-conductor) o a un guardián
ALTER TABLE MENSAJES ADD CONSTRAINT FK_MENSAJES_SOLICITUD
    FOREIGN KEY(SOLICITUD_ID_SOL)
    REFERENCES SOLICITUDES (ID_SOL)
    ON DELETE CASCADE;
ALTER TABLE MENSAJES ADD CONSTRAINT FK_MENSAJES_GUARDIAN
    FOREIGN KEY(GUARDIAN_ID_GUA)
    REFERENCES GUARDIANES (ID_GUA)
    ON DELETE CASCADE;

-- ==========================================================
-- SEGURIDAD (Supabase)
-- Supabase publica el esquema public por su API REST (PostgREST) con la
-- anon key. RLS sin políticas bloquea ese acceso; la aplicación se conecta
-- directo con el usuario dueño de las tablas, que no queda afectado.
-- ==========================================================

ALTER TABLE ROLES ENABLE ROW LEVEL SECURITY;
ALTER TABLE MENUS ENABLE ROW LEVEL SECURITY;
ALTER TABLE PERFILES ENABLE ROW LEVEL SECURITY;
ALTER TABLE USUARIOS ENABLE ROW LEVEL SECURITY;
ALTER TABLE PERMISOS ENABLE ROW LEVEL SECURITY;
ALTER TABLE MARCAS ENABLE ROW LEVEL SECURITY;
ALTER TABLE DEPARTAMENTOS ENABLE ROW LEVEL SECURITY;
ALTER TABLE MUNICIPIOS ENABLE ROW LEVEL SECURITY;
ALTER TABLE ESTADOS_SOL ENABLE ROW LEVEL SECURITY;
ALTER TABLE ESTADOS_VIA ENABLE ROW LEVEL SECURITY;
ALTER TABLE ESTADOS_GUA ENABLE ROW LEVEL SECURITY;
ALTER TABLE VEHICULOS ENABLE ROW LEVEL SECURITY;
ALTER TABLE VIAJES ENABLE ROW LEVEL SECURITY;
ALTER TABLE MENSAJES ENABLE ROW LEVEL SECURITY;
ALTER TABLE SOLICITUDES ENABLE ROW LEVEL SECURITY;
ALTER TABLE GUARDIANES ENABLE ROW LEVEL SECURITY;

COMMIT;
